openapi: 3.0.0
info:
  title: DesiredConditionSelectValues Controller Schema
  version: 1.0.0

paths:
  /desiredConditionSelectValues:
    get:
      operationId: DesiredConditionSelectValues
      description: 希望条件編集のセレクトボックスのオプション取得
      parameters: []
      responses:
        '200':
          description: 希望条件編集のセレクトボックスのオプション取得成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DesiredConditionSelectValues'
        '400':
          $ref: '../errors.yml#responses/400'
        '401':
          $ref: '../errors.yml#responses/401'
        '404':
          $ref: '../errors.yml#responses/404'

components:
  schemas:
    DesiredConditionSelectValues:
      $ref: './components/desired_condition_select_values.dto.yml'
