openapi: 3.0.0
info:
  title: ProfileSelectValues Controller Schema
  version: 1.0.0
paths:
  /profileSelectValues:
    get:
      operationId: ProfileSelectValues
      description: プロフィール編集のセレクトボックスのオプション取得
      parameters: []
      responses:
        '200':
          description: プロフィール編集のセレクトボックスのオプション取得成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileSelectValues'
        '400':
          description: バリデーションエラー
          content:
            application/json:
              schema:
                description: バリデーションエラー
                type: object
                properties:
                  statusCode:
                    type: number
                  message:
                    type: array
                    items:
                      description: TODO取得時のレスポンスのDTO
                      type: string
                  error:
                    type: string
                required:
                  - statusCode
                  - message
                  - error
        '401':
          description: 認証エラー
          content:
            application/json:
              schema:
                description: 認証エラー
                type: object
                properties:
                  statusCode:
                    type: number
                  message:
                    type: string
                required:
                  - statusCode
                  - message
        '404':
          description: Not Foundエラー
          content:
            application/json:
              schema:
                description: Not Foundエラー
                type: object
                properties:
                  statusCode:
                    type: number
                  message:
                    type: string
                required:
                  - statusCode
                  - message
components:
  schemas:
    ProfileSelectValues:
      description: 編集対象のプロフィール取得レスポンスのDTO
      type: object
      properties:
        currentEmployment:
          type: array
          items:
            type: object
            properties:
              value:
                type: string
              name:
                type: string
            required:
              - value
              - name
        experiencedDuration:
          type: array
          items:
            type: object
            properties:
              value:
                type: string
              name:
                type: string
            required:
              - value
              - name
        experiencedEntityDuration:
          type: array
          items:
            type: object
            properties:
              value:
                type: string
              name:
                type: string
            required:
              - value
              - name
      required:
        - currentEmployment
        - experiencedDuration
        - experiencedEntityDuration
