import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import StyledComponentsRegistry from '@/lib/registry';
import { SignUpProvider } from '@/features/auth/contexts/SignUpContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<StyledComponentsRegistry>
				<SignUpProvider>
					<body className={inter.className}>{children}</body>
				</SignUpProvider>
			</StyledComponentsRegistry>
		</html>
	);
}
