openapi: 3.0.0
info:
  title: Desired Conditions Controller Schema
  version: 1.0.0

paths:
  /desiredConditions:
    post:
      operationId: updateDesiredCondition
      description: ログインユーザの希望条件を更新
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateDesiredConditionDto'
      responses:
        '201':
          description: 希望条件の更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateDesiredConditionResponseDto'
        '400':
          $ref: '../errors.yml#responses/400'
        '401':
          $ref: '../errors.yml#responses/401'
    get:
      operationId: findForDesiredConditionEdit
      description: 編集対象となるログインユーザの希望条件を取得
      parameters: []
      responses:
        '200':
          description: 希望条件の取得成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DesiredConditionForEditDto'
        '400':
          $ref: '../errors.yml#responses/400'
        '401':
          $ref: '../errors.yml#responses/401'
        '404':
          $ref: '../errors.yml#responses/404'

components:
  schemas:
    DesiredConditionForEditDto:
      $ref: './components/desired_condition_for_edit.dto.yml'
    UpdateDesiredConditionDto:
      $ref: './components/update_desired_condition.dto.yml'
    UpdateDesiredConditionResponseDto:
      $ref: './components/update_desired_condition_response.dto.yml'
