openapi: 3.0.0
info:
  title: Todos Controller Schema
  version: 1.0.0

paths:
  /auth/validate_sign_up:
    post:
      operationId: validateSignUp
      description: 会員登録の入力バリデーション
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpDto'
      responses:
        '200':
          description: バリデーションエラーの返却
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidateSignUpResponseDto'
  /auth/sign_up:
    post:
      operationId: signUp
      description: 会員登録
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpDto'
      responses:
        '200':
          description: 会員登録成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignUpResponseDto'
  /auth/sign_in:
    post:
      operationId: signIn
      description: ログイン
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInDto'
      responses:
        '200':
          description: ログイン成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignInResponseDto'
        '400':
          description: バリデーションエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponseDto'
components:
  schemas:
    SignUpDto:
      $ref: './components/sign_up.dto.yml'
    ValidateSignUpResponseDto:
      $ref: './components/validate_sign_up_response.dto.yml'
    SignUpResponseDto:
      $ref: './components/sign_up_response.dto.yml'
    SignInDto:
      $ref: './components/sign_in.dto.yml'
    SignInResponseDto:
      $ref: './components/sign_in_response.dto.yml'
    ValidationErrorResponseDto:
      $ref: '../errors.yml#components/schemas/ValidationError'
